apiVersion: identity.cnrm.cloud.google.com/v1alpha2
kind: IdentityNamespace
metadata:
  name: default
  namespace: "nanyu-gke-dev" # {"type":"string","x-kustomize":{"setter":{"name":"gcloud.core.project","value":"nanyu-gke-dev"}}}
spec: {}
